services:
  - type: web
    name: django-tailwind-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rugipo_chatbot.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
    plan: free
